//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrmComponents.Discovery_92_Online {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DiscoveryRequest", Namespace="http://schemas.microsoft.com/xrm/2011/Contracts/Discovery")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CrmComponents.Discovery_92_Online.RetrieveOrganizationRequestModel))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CrmComponents.Discovery_92_Online.RetrieveOrganizationsRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CrmComponents.Discovery_92_Online.RetrieveUserIdByExternalIdRequest))]
    public partial class DiscoveryRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RetrieveOrganizationRequestModel", Namespace="http://schemas.microsoft.com/xrm/2011/Contracts/Discovery")]
    [System.SerializableAttribute()]
    public partial class RetrieveOrganizationRequestModel : CrmComponents.Discovery_92_Online.DiscoveryRequest {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CrmComponents.Discovery_92_Online.EndpointAccessType AccessTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CrmComponents.Discovery_92_Online.OrganizationRelease ReleaseField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UniqueNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CrmComponents.Discovery_92_Online.EndpointAccessType AccessType {
            get {
                return this.AccessTypeField;
            }
            set {
                if ((this.AccessTypeField.Equals(value) != true)) {
                    this.AccessTypeField = value;
                    this.RaisePropertyChanged("AccessType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CrmComponents.Discovery_92_Online.OrganizationRelease Release {
            get {
                return this.ReleaseField;
            }
            set {
                if ((this.ReleaseField.Equals(value) != true)) {
                    this.ReleaseField = value;
                    this.RaisePropertyChanged("Release");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UniqueName {
            get {
                return this.UniqueNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UniqueNameField, value) != true)) {
                    this.UniqueNameField = value;
                    this.RaisePropertyChanged("UniqueName");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RetrieveOrganizationsRequest", Namespace="http://schemas.microsoft.com/xrm/2011/Contracts/Discovery")]
    [System.SerializableAttribute()]
    public partial class RetrieveOrganizationsRequest : CrmComponents.Discovery_92_Online.DiscoveryRequest {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CrmComponents.Discovery_92_Online.EndpointAccessType AccessTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsInternalCrossGeoServerRequestField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CrmComponents.Discovery_92_Online.OrganizationRelease ReleaseField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CrmComponents.Discovery_92_Online.EndpointAccessType AccessType {
            get {
                return this.AccessTypeField;
            }
            set {
                if ((this.AccessTypeField.Equals(value) != true)) {
                    this.AccessTypeField = value;
                    this.RaisePropertyChanged("AccessType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsInternalCrossGeoServerRequest {
            get {
                return this.IsInternalCrossGeoServerRequestField;
            }
            set {
                if ((this.IsInternalCrossGeoServerRequestField.Equals(value) != true)) {
                    this.IsInternalCrossGeoServerRequestField = value;
                    this.RaisePropertyChanged("IsInternalCrossGeoServerRequest");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CrmComponents.Discovery_92_Online.OrganizationRelease Release {
            get {
                return this.ReleaseField;
            }
            set {
                if ((this.ReleaseField.Equals(value) != true)) {
                    this.ReleaseField = value;
                    this.RaisePropertyChanged("Release");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RetrieveUserIdByExternalIdRequest", Namespace="http://schemas.microsoft.com/xrm/2011/Contracts/Discovery")]
    [System.SerializableAttribute()]
    public partial class RetrieveUserIdByExternalIdRequest : CrmComponents.Discovery_92_Online.DiscoveryRequest {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExternalIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid OrganizationIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OrganizationNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReleaseField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ExternalId {
            get {
                return this.ExternalIdField;
            }
            set {
                if ((object.ReferenceEquals(this.ExternalIdField, value) != true)) {
                    this.ExternalIdField = value;
                    this.RaisePropertyChanged("ExternalId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid OrganizationId {
            get {
                return this.OrganizationIdField;
            }
            set {
                if ((this.OrganizationIdField.Equals(value) != true)) {
                    this.OrganizationIdField = value;
                    this.RaisePropertyChanged("OrganizationId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OrganizationName {
            get {
                return this.OrganizationNameField;
            }
            set {
                if ((object.ReferenceEquals(this.OrganizationNameField, value) != true)) {
                    this.OrganizationNameField = value;
                    this.RaisePropertyChanged("OrganizationName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Release {
            get {
                return this.ReleaseField;
            }
            set {
                if ((object.ReferenceEquals(this.ReleaseField, value) != true)) {
                    this.ReleaseField = value;
                    this.RaisePropertyChanged("Release");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EndpointAccessType", Namespace="http://schemas.microsoft.com/xrm/2011/Contracts/Discovery")]
    public enum EndpointAccessType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Default = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Internet = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Intranet = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OrganizationRelease", Namespace="http://schemas.microsoft.com/xrm/2011/Contracts/Discovery")]
    public enum OrganizationRelease : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Current = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        V5 = 1,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DiscoveryResponse", Namespace="http://schemas.microsoft.com/xrm/2011/Contracts/Discovery")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CrmComponents.Discovery_92_Online.RetrieveOrganizationResponseModel))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CrmComponents.Discovery_92_Online.RetrieveOrganizationsResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CrmComponents.Discovery_92_Online.RetrieveUserIdByExternalIdResponse))]
    public partial class DiscoveryResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RetrieveOrganizationResponseModel", Namespace="http://schemas.microsoft.com/xrm/2011/Contracts/Discovery")]
    [System.SerializableAttribute()]
    public partial class RetrieveOrganizationResponseModel : CrmComponents.Discovery_92_Online.DiscoveryResponse {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CrmComponents.Discovery_92_Online.OrganizationDetail DetailField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CrmComponents.Discovery_92_Online.OrganizationDetail Detail {
            get {
                return this.DetailField;
            }
            set {
                if ((object.ReferenceEquals(this.DetailField, value) != true)) {
                    this.DetailField = value;
                    this.RaisePropertyChanged("Detail");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RetrieveOrganizationsResponse", Namespace="http://schemas.microsoft.com/xrm/2011/Contracts/Discovery")]
    [System.SerializableAttribute()]
    public partial class RetrieveOrganizationsResponse : CrmComponents.Discovery_92_Online.DiscoveryResponse {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CrmComponents.Discovery_92_Online.OrganizationDetailCollection DetailsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CrmComponents.Discovery_92_Online.OrganizationDetailCollection Details {
            get {
                return this.DetailsField;
            }
            set {
                if ((object.ReferenceEquals(this.DetailsField, value) != true)) {
                    this.DetailsField = value;
                    this.RaisePropertyChanged("Details");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RetrieveUserIdByExternalIdResponse", Namespace="http://schemas.microsoft.com/xrm/2011/Contracts/Discovery")]
    [System.SerializableAttribute()]
    public partial class RetrieveUserIdByExternalIdResponse : CrmComponents.Discovery_92_Online.DiscoveryResponse {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid UserIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid UserId {
            get {
                return this.UserIdField;
            }
            set {
                if ((this.UserIdField.Equals(value) != true)) {
                    this.UserIdField = value;
                    this.RaisePropertyChanged("UserId");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OrganizationDetail", Namespace="http://schemas.microsoft.com/xrm/2011/Contracts/Discovery")]
    [System.SerializableAttribute()]
    public partial class OrganizationDetail : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CrmComponents.Discovery_92_Online.EndpointCollection EndpointsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FriendlyNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid OrganizationIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OrganizationVersionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CrmComponents.Discovery_92_Online.OrganizationState StateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UniqueNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UrlNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CrmComponents.Discovery_92_Online.EndpointCollection Endpoints {
            get {
                return this.EndpointsField;
            }
            set {
                if ((object.ReferenceEquals(this.EndpointsField, value) != true)) {
                    this.EndpointsField = value;
                    this.RaisePropertyChanged("Endpoints");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FriendlyName {
            get {
                return this.FriendlyNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FriendlyNameField, value) != true)) {
                    this.FriendlyNameField = value;
                    this.RaisePropertyChanged("FriendlyName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid OrganizationId {
            get {
                return this.OrganizationIdField;
            }
            set {
                if ((this.OrganizationIdField.Equals(value) != true)) {
                    this.OrganizationIdField = value;
                    this.RaisePropertyChanged("OrganizationId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OrganizationVersion {
            get {
                return this.OrganizationVersionField;
            }
            set {
                if ((object.ReferenceEquals(this.OrganizationVersionField, value) != true)) {
                    this.OrganizationVersionField = value;
                    this.RaisePropertyChanged("OrganizationVersion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CrmComponents.Discovery_92_Online.OrganizationState State {
            get {
                return this.StateField;
            }
            set {
                if ((this.StateField.Equals(value) != true)) {
                    this.StateField = value;
                    this.RaisePropertyChanged("State");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UniqueName {
            get {
                return this.UniqueNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UniqueNameField, value) != true)) {
                    this.UniqueNameField = value;
                    this.RaisePropertyChanged("UniqueName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UrlName {
            get {
                return this.UrlNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UrlNameField, value) != true)) {
                    this.UrlNameField = value;
                    this.RaisePropertyChanged("UrlName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="EndpointCollection", Namespace="http://schemas.microsoft.com/xrm/2011/Contracts/Discovery", ItemName="KeyValuePairOfEndpointTypestringztYlk6OT")]
    [System.SerializableAttribute()]
    public class EndpointCollection : System.Collections.Generic.List<System.Collections.Generic.KeyValuePair<CrmComponents.Discovery_92_Online.EndpointType, string>> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OrganizationState", Namespace="http://schemas.microsoft.com/xrm/2011/Contracts/Discovery")]
    public enum OrganizationState : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Enabled = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Disabled = 1,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EndpointType", Namespace="http://schemas.microsoft.com/xrm/2011/Contracts/Discovery")]
    public enum EndpointType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OrganizationService = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OrganizationDataService = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        WebApplication = 2,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="OrganizationDetailCollection", Namespace="http://schemas.microsoft.com/xrm/2011/Contracts/Discovery", ItemName="OrganizationDetail")]
    [System.SerializableAttribute()]
    public class OrganizationDetailCollection : System.Collections.Generic.List<CrmComponents.Discovery_92_Online.OrganizationDetail> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseServiceFault", Namespace="http://schemas.microsoft.com/xrm/2011/Contracts")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CrmComponents.Discovery_92_Online.OrganizationServiceFault))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CrmComponents.Discovery_92_Online.ExecuteTransactionFault))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CrmComponents.Discovery_92_Online.DiscoveryServiceFault))]
    public partial class BaseServiceFault : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ErrorCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CrmComponents.Discovery_92_Online.ErrorDetailCollection ErrorDetailsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime TimestampField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ErrorCode {
            get {
                return this.ErrorCodeField;
            }
            set {
                if ((this.ErrorCodeField.Equals(value) != true)) {
                    this.ErrorCodeField = value;
                    this.RaisePropertyChanged("ErrorCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CrmComponents.Discovery_92_Online.ErrorDetailCollection ErrorDetails {
            get {
                return this.ErrorDetailsField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorDetailsField, value) != true)) {
                    this.ErrorDetailsField = value;
                    this.RaisePropertyChanged("ErrorDetails");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Timestamp {
            get {
                return this.TimestampField;
            }
            set {
                if ((this.TimestampField.Equals(value) != true)) {
                    this.TimestampField = value;
                    this.RaisePropertyChanged("Timestamp");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OrganizationServiceFault", Namespace="http://schemas.microsoft.com/xrm/2011/Contracts")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CrmComponents.Discovery_92_Online.ExecuteTransactionFault))]
    public partial class OrganizationServiceFault : CrmComponents.Discovery_92_Online.BaseServiceFault {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CrmComponents.Discovery_92_Online.OrganizationServiceFault InnerFaultField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TraceTextField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CrmComponents.Discovery_92_Online.OrganizationServiceFault InnerFault {
            get {
                return this.InnerFaultField;
            }
            set {
                if ((object.ReferenceEquals(this.InnerFaultField, value) != true)) {
                    this.InnerFaultField = value;
                    this.RaisePropertyChanged("InnerFault");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TraceText {
            get {
                return this.TraceTextField;
            }
            set {
                if ((object.ReferenceEquals(this.TraceTextField, value) != true)) {
                    this.TraceTextField = value;
                    this.RaisePropertyChanged("TraceText");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ExecuteTransactionFault", Namespace="http://schemas.microsoft.com/xrm/7.1/Contracts")]
    [System.SerializableAttribute()]
    public partial class ExecuteTransactionFault : CrmComponents.Discovery_92_Online.OrganizationServiceFault {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int FaultedRequestIndexField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int FaultedRequestIndex {
            get {
                return this.FaultedRequestIndexField;
            }
            set {
                if ((this.FaultedRequestIndexField.Equals(value) != true)) {
                    this.FaultedRequestIndexField = value;
                    this.RaisePropertyChanged("FaultedRequestIndex");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DiscoveryServiceFault", Namespace="http://schemas.microsoft.com/xrm/2011/Contracts")]
    [System.SerializableAttribute()]
    public partial class DiscoveryServiceFault : CrmComponents.Discovery_92_Online.BaseServiceFault {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CrmComponents.Discovery_92_Online.DiscoveryServiceFault InnerFaultField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CrmComponents.Discovery_92_Online.DiscoveryServiceFault InnerFault {
            get {
                return this.InnerFaultField;
            }
            set {
                if ((object.ReferenceEquals(this.InnerFaultField, value) != true)) {
                    this.InnerFaultField = value;
                    this.RaisePropertyChanged("InnerFault");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ErrorDetailCollection", Namespace="http://schemas.microsoft.com/xrm/2011/Contracts", ItemName="KeyValuePairOfstringanyType")]
    [System.SerializableAttribute()]
    public class ErrorDetailCollection : System.Collections.Generic.List<System.Collections.Generic.KeyValuePair<string, object>> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/Contracts/Discovery", ConfigurationName="Discovery_92_Online.IDiscoveryService")]
    public interface IDiscoveryService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/xrm/2011/Contracts/Discovery/IDiscoveryService/Execu" +
            "te", ReplyAction="http://schemas.microsoft.com/xrm/2011/Contracts/Discovery/IDiscoveryService/Execu" +
            "teResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(CrmComponents.Discovery_92_Online.DiscoveryServiceFault), Action="http://schemas.microsoft.com/xrm/2011/Contracts/Discovery/IDiscoveryService/Execu" +
            "teDiscoveryServiceFaultFault", Name="DiscoveryServiceFault", Namespace="http://schemas.microsoft.com/xrm/2011/Contracts")]
        CrmComponents.Discovery_92_Online.DiscoveryResponse Execute(CrmComponents.Discovery_92_Online.DiscoveryRequest request);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDiscoveryServiceChannel : CrmComponents.Discovery_92_Online.IDiscoveryService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DiscoveryServiceClient : System.ServiceModel.ClientBase<CrmComponents.Discovery_92_Online.IDiscoveryService>, CrmComponents.Discovery_92_Online.IDiscoveryService {
        
        public DiscoveryServiceClient() {
        }
        
        public DiscoveryServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DiscoveryServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DiscoveryServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DiscoveryServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public CrmComponents.Discovery_92_Online.DiscoveryResponse Execute(CrmComponents.Discovery_92_Online.DiscoveryRequest request) {
            return base.Channel.Execute(request);
        }
    }
}
